route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '#<channel-name>'
            api_url: 'https://hooks.slack.com/services/<webhook-id>'

#    - name: 'telegram'
#      telegram_configs:
#        - bot_token: '6314535569:AAFAXfaJIX2ZZab-aK86Jg_O5tB8qXBaAvo'
#            chat_id: -951543354
#             chat_id: -4080003674
#            send_resolved: true
#            api_url: "https://api.telegram.org"
