# конфигурационный файл prometheus для настройки параметров
global:
  scrape_interval: 15s  # Интервал сбора scrape_interval определяет, как часто будет опрашиваться целевой контейнер
  evaluation_interval: 15s  # интервал обработки evaluation_interval задает частоту выполнения правил обработки.

# Добавить метку для графического представления
  external_labels:
    monitor: 'Docker-pk-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself
scrape_configs:
# Конечные точки для сбора информации здесь ам prometheus
  - job_name: 'pk_prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

# добавление целей мониторинга для prometheus
  - job_name: 'pk_node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'nodeexporter:9100' ]

  - job_name: 'pk_cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'cadvisor:8080' ]

  - job_name: 'docker'
    scrape_interval: 20s
    static_configs:
      - targets: [ 'localhost:9323' ]

  - job_name: 'pk_db'
    scrape_interval: 20s
    static_configs:
      - targets: [ 'db:6379' ]

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'