{
 "title": "Docker Logs",
 "tags": [ "logs" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Errors and Warnings",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{compose_project=\"app\", container_name=~\"bot|db\"} |~ `ERROR|WARNING` "
    }
   ]
  },
  {
   "title": "Error and Warning rates",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate({compose_project=\"app\", container_name=~\"bot|db|bot_moderator\"} |~ `ERROR|WARNING` [1m])"
    }
   ]
  },
  {
   "title": "Support Bot logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{container_name=\"bot\"}"
    }
   ]
  },
  {
   "title": "Redis Database Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{container_name=\"db\"}"
    }
   ]
  },
  {
   "title": "Bot Moderator Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{container_name=\"bot_moderator\"}"
    }
   ]
  }
 ]
}