server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

#scrape_configs:
#- job_name: system
#  static_configs:
#  - targets:
#      - 127.0.0.1
#    labels:
#      job: varlogs
#      __path__: /var/log/*log


# docker plugin install grafana/loki-docker-driver:2.9.1 --alias loki --grant-all-permissions
scrape_configs:
  - job_name: docker
    static_configs:
      - labels:
          job: docker
          __path__: /var/log/*log
